### ISSUE TITLE
Relax SSHKit dependency

### ISSUE THREAD

**Issue by tanelsuurhans** [ydkn/sshkit-interact#1]
There is a 1.8.1 version out for SSHKit, with hopefully a new release coming out soon that fixes a pretty critical issue how this gem taps into the capistrano and SSHKit backend logic (https://github.com/capistrano/sshkit/pull/320). Can you please relax the gem dependency to either just 1.7 or 1.8.0 and make another release.

**Comment by tisba** [comment]
sshkit is at 1.11.1 now, would be great if we could update the requirements here…

**Comment by code-later** [comment]
I tested the upgrade and all that was required can be found here: https://github.com/ydkn/sshkit-interact/compare/master...fejo-dk:use-sshkit-1.11

This works for our use case but I'm not familiar enough with SSHKit itself to check if this covers all requirements. Additionally this changes the interface for the interact method slightly. Would be great if someone could look into it, try it out and give me some feedback. Would be happy to open a PR if this does the job.

**Comment by ydkn** [comment]
Sorry for the very late answer guys. This gem was an experiment which I dropped in favor of contributing to https://github.com/afeld/sshkit-interactive.
I will implement the features that I have envisioned with _sshkit-interact_ there.
If for some reason someone likes to maintain this gem instead - please let me know.
